# Generated by Django 2.2.26 on 2022-05-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_testdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="testdata",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
