# Generated by Django 2.2.26 on 2022-05-13 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_testdata_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testdata',
            name='address',
        ),
    ]
